"""
dotplot_inputs.py

Provides utilities for generating FASTA inputs for anchor-vs.-partners
dotplot inspection.

Functions
---------
_sanitize_path_component    : Convert an arbitrary identifier into a filesystem-safe path name.
_build_partner_header       : Build a traceable FASTA header for one partner sequence.
write_anchor_dotplot_fastas : Generate per-anchor FASTA inputs for plottable overlaps.
"""

# --------------------------------------------------------------------------------------
# Imports
# --------------------------------------------------------------------------------------
from __future__ import annotations
import csv
from collections import defaultdict
import hashlib
from pathlib import Path

from atomization_scorer.data_processing import read_fasta, write_fasta
from atomization_scorer.diagnostics.overlap_diagnostics import OVERLAP_FIELDNAMES

# --------------------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------------------
PAIR_FIELDNAMES = OVERLAP_FIELDNAMES


# --------------------------------------------------------------------------------------
# Path Sanitization
# --------------------------------------------------------------------------------------
def _sanitize_path_component(value: str) -> str:
    """
    Convert an arbitrary identifier into a filesystem-safe directory name.

    Parameters
    ----------
    value : str
        Input identifier to sanitize for filesystem use.

    Returns
    -------
    str
        Sanitized path component safe for use as a directory name.
    """
    safe_characters = {"-", "_", "."}
    sanitized = "".join(
        character if character.isalnum() or character in safe_characters else "_"
        for character in value
    ).strip("_")

    if sanitized:
        return sanitized

    digest = hashlib.sha1(value.encode("utf-8")).hexdigest()[:8]
    return f"anchor_{digest}"


# --------------------------------------------------------------------------------------
# Partner Header Builder
# --------------------------------------------------------------------------------------
def _build_partner_header(entry: dict[str, str]) -> str:
    """
    Create a concise FASTA header for one partner sequence.

    Parameters
    ----------
    entry : dict[str, str]
        Overlap record for one anchor-partner pair.

    Returns
    -------
    str
        Concise FASTA header containing only the partner atom.
    """
    return f"partner={entry['partner_atom']}"


# --------------------------------------------------------------------------------------
# Dotplot FASTA Generation
# --------------------------------------------------------------------------------------
def write_anchor_dotplot_fastas(
    overlaps: list[dict[str, str]],
    representatives_fasta: Path,
    output_directory: Path,
    minimum_overlap_length: int,
    include_reverse: bool = False,
) -> Path:
    """
    Generate per-anchor FASTA inputs for plottable overlaps.

    Parameters
    ----------
    overlaps : list[dict[str, str]]
        Overlap records generated by the overlap diagnostics workflow.
    representatives_fasta : Path
        FASTA file containing representative atom sequences.
    output_directory : Path
        Directory where anchor FASTA files should be written.
    minimum_overlap_length : int
        Minimum overlap length required to emit dotplot inputs.
    include_reverse : bool, optional, default=False
        Whether to also emit reverse anchor-partner entries so each overlap appears
        from both anchor perspectives.

    Raises
    ------
    ValueError
        Raised if an anchor or partner atom is missing from the representatives FASTA.

    Returns
    -------
    Path
        Directory containing anchor-specific FASTA files.
    """
    output_directory.mkdir(parents=True, exist_ok=True)

    representatives = read_fasta(representatives_fasta)
    anchor_entries = defaultdict(list)

    for overlap in overlaps:
        overlap_length = int(overlap["overlap_length"])
        if overlap_length < minimum_overlap_length:
            continue

        anchor_entries[overlap["anchor_atom"]].append(overlap)
        if include_reverse:
            reverse_entry = {
                "query_name": overlap["query_name"],
                "anchor_atom": overlap["partner_atom"],
                "partner_atom": overlap["anchor_atom"],
                "anchor_query_start": overlap["partner_query_start"],
                "anchor_query_end": overlap["partner_query_end"],
                "partner_query_start": overlap["anchor_query_start"],
                "partner_query_end": overlap["anchor_query_end"],
                "anchor_target_start": overlap["partner_target_start"],
                "anchor_target_end": overlap["partner_target_end"],
                "partner_target_start": overlap["anchor_target_start"],
                "partner_target_end": overlap["anchor_target_end"],
                "anchor_strand": overlap["partner_strand"],
                "partner_strand": overlap["anchor_strand"],
                "overlap_start": overlap["overlap_start"],
                "overlap_end": overlap["overlap_end"],
                "overlap_length": overlap["overlap_length"],
                "overlap_class": overlap["overlap_class"],
            }
            anchor_entries[reverse_entry["anchor_atom"]].append(reverse_entry)

    for anchor_atom, entries in anchor_entries.items():
        if anchor_atom not in representatives:
            raise ValueError(f"Representative FASTA is missing anchor atom: {anchor_atom}")

        anchor_directory = output_directory / _sanitize_path_component(anchor_atom)
        anchor_directory.mkdir(parents=True, exist_ok=True)

        anchor_sequence = representatives[anchor_atom]
        write_fasta(
            sequences={f"anchor={anchor_atom}": anchor_sequence},
            output_path=anchor_directory / "X.fasta",
        )

        partner_sequences = {}
        pair_rows = []

        for index, entry in enumerate(
            sorted(
                entries,
                key=lambda item: (
                    -int(item["overlap_length"]),
                    item["partner_atom"],
                    item["query_name"],
                ),
            ),
            start=1,
        ):
            partner_atom = entry["partner_atom"]
            if partner_atom not in representatives:
                raise ValueError(f"Representative FASTA is missing partner atom: {partner_atom}")

            partner_header = _build_partner_header(entry)
            partner_sequences[partner_header] = representatives[partner_atom]
            pair_rows.append(entry)

        if partner_sequences:
            write_fasta(sequences=partner_sequences, output_path=anchor_directory / "Y.fasta")

        with (anchor_directory / "pairs.tsv").open("w", newline="") as file:
            writer = csv.DictWriter(file, fieldnames=PAIR_FIELDNAMES, delimiter="\t")
            writer.writeheader()
            writer.writerows(pair_rows)

    return output_directory
